// Package service provides systemd unit generation + lifecycle commands shared
// by the client and natclient binaries (which have no web console). Each role
// gets a plain `deepseek-<role>.service` unit generated from the *current*
// executable and config paths, with enable kept separate from start.
package service

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"text/template"
)

// RoleUnitName returns e.g. "deepseek-client.service" / "deepseek-natclient.service".
func RoleUnitName(role string) string { return "deepseek-" + role + ".service" }

// UnitDir returns where unit files are written; overridable for tests.
func UnitDir() string {
	if d := os.Getenv("DEEPSEEK_SYSTEMD_DIR"); d != "" {
		return d
	}
	return "/etc/systemd/system"
}

// RoleUnitPath returns the full path of the unit for role.
func RoleUnitPath(role string) string { return filepath.Join(UnitDir(), RoleUnitName(role)) }

// SystemdActive reports whether systemd is the running init (manager present).
func SystemdActive() bool {
	_, err := os.Stat("/run/systemd/system")
	return err == nil
}

// CurrentUser resolves the run account (name + group) for the unit, honoring
// the DEEPSEEK_SERVICE_USER override.
func CurrentUser() (name, group string) {
	name = "nobody"
	group = "nogroup"
	if u, err := user.Current(); err == nil && u.Username != "" {
		name = u.Username
		group = u.Gid
		if g, gerr := user.LookupGroup(u.Gid); gerr == nil && g.Name != "" {
			group = g.Name
		}
	}
	if e := os.Getenv("DEEPSEEK_SERVICE_USER"); e != "" {
		name = e
		if u, err := user.Lookup(name); err == nil {
			if g, gerr := user.LookupGroup(u.Gid); gerr == nil && g.Name != "" {
				group = g.Name
			}
		}
	}
	return name, group
}

// RenderUnit renders the unit content for a client / natclient role.
func RenderUnit(role, exe, cfgPath, runUser, runGroup string) ([]byte, error) {
	absCfg, err := filepath.Abs(cfgPath)
	if err != nil || absCfg == "" {
		absCfg = cfgPath
	}
	absExe, err := filepath.EvalSymlinks(exe)
	if err != nil {
		absExe = exe
	}
	desc := "DeepSeek AI tunnel client (entry endpoint)"
	if role == "natclient" {
		desc = "DeepSeek AI tunnel NAT client (exposes local services via server)"
	}
	tpl := template.Must(template.New("unit").Parse(`# Generated by deepseek-` + role + ` (service install). Edits may be overwritten.
[Unit]
Description={{.Desc}}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={{.User}}
Group={{.Group}}
ExecStart={{.Exe}} -config {{.Config}}
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only

[Install]
WantedBy=multi-user.target
`))
	var b strings.Builder
	err = tpl.Execute(&b, struct {
		Desc, User, Group, Exe, Config string
	}{desc, runUser, runGroup, absExe, absCfg})
	if err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// InstallUnit writes the unit (atomic) and daemon-reloads. Returns the path.
func InstallUnit(role, cfgPath string) (string, error) {
	exe, _ := os.Executable()
	u, g := CurrentUser()
	content, err := RenderUnit(role, exe, cfgPath, u, g)
	if err != nil {
		return "", err
	}
	path := RoleUnitPath(role)
	if err := atomicWriteFile(path, content); err != nil {
		return "", fmt.Errorf("写入单元文件 %s: %w (需要 root 权限?)", path, err)
	}
	if out, err := Sysctl("daemon-reload"); err != nil {
		_ = out // best effort
	}
	return path, nil
}

// Sysctl runs `systemctl <args...>` and returns its trimmed combined output.
func Sysctl(args ...string) (string, error) {
	out, err := exec.Command("systemctl", args...).CombinedOutput()
	return strings.TrimSpace(string(out)), err
}
