package main

// systemd service management for the web console + CLI. It renders the
// deepseek-server.service unit from the *current* executable and config paths,
// writes it, and controls enable/start (kept separate). Starting performs a
// graceful handoff: when the running process was launched via `start` (daemon)
// or in the foreground (not already under systemd), it closes its listeners
// (freeing the port), asks systemd to take over, then exits cleanly so the
// service mode owns the port and reads the SAME config file as the console.

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"deepseekaiworker/internal/admin"
)

// serviceUnitDir returns where unit files are written. Overridable (tests).
func serviceUnitDir() string {
	if d := os.Getenv("DEEPSEEK_SYSTEMD_DIR"); d != "" {
		return d
	}
	return "/etc/systemd/system"
}

func serviceUnitName() string { return "deepseek-server.service" }
func serviceUnitPath() string { return filepath.Join(serviceUnitDir(), serviceUnitName()) }

// hostSystemdActive reports whether this host runs systemd (not whether THIS
// process is a systemd service).
func hostSystemdActive() bool {
	if os.Getenv("INVOCATION_ID") != "" {
		return true
	}
	_, err := os.Stat("/run/systemd/system")
	return err == nil
}

// underSystemd reports whether the current process is itself a systemd service.
func underSystemd() bool { return os.Getenv("INVOCATION_ID") != "" }

// currentRunUser resolves the account the service should run as.
func currentRunUser() (name, group string) {
	name = "nobody"
	group = "nogroup"
	if u, err := user.Current(); err == nil && u.Username != "" {
		name = u.Username
		group = u.Gid
		if g, gerr := user.LookupGroup(u.Gid); gerr == nil && g.Name != "" {
			group = g.Name
		}
	}
	if e := os.Getenv("DEEPSEEK_SERVICE_USER"); e != "" {
		name = e
		// group follows: try to resolve group of that user, else keep
		if u, err := user.Lookup(name); err == nil {
			if g, gerr := user.LookupGroup(u.Gid); gerr == nil && g.Name != "" {
				group = g.Name
			}
		}
	}
	return name, group
}

// renderServerUnit returns the unit content for the given executable/config/user.
func renderServerUnit(exe, cfgPath, runUser, runGroup string) ([]byte, error) {
	absCfg, err := filepath.Abs(cfgPath)
	if err != nil || absCfg == "" {
		absCfg = cfgPath
	}
	absExe, err := filepath.EvalSymlinks(exe)
	if err != nil {
		absExe = exe
	}
	cfgDir := filepath.Dir(absCfg)
	tpl := template.Must(template.New("unit").Parse(`# Generated by deepseek-server (web console). Edits here may be overwritten;
# use the console 服务(service) page to manage this unit.
[Unit]
Description=DeepSeek AI tunnel server (TLS relay hub + web console)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={{.User}}
Group={{.Group}}
ExecStart={{.Exe}} run -config {{.Config}}
WorkingDirectory={{.ConfigDir}}
Restart=always
RestartSec=3
ReadWritePaths={{.ConfigDir}}
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
`))
	var b strings.Builder
	if err := tpl.Execute(&b, struct {
		User, Group, Exe, Config, ConfigDir string
	}{runUser, runGroup, absExe, absCfg, cfgDir}); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// installServiceUnit writes the unit file (atomic) and daemon-reloads.
func installServiceUnit(cfgPath string) (string, error) {
	exe, _ := os.Executable()
	u, g := currentRunUser()
	content, err := renderServerUnit(exe, cfgPath, u, g)
	if err != nil {
		return "", err
	}
	path := serviceUnitPath()
	if err := atomicWriteFile(path, content); err != nil {
		return "", fmt.Errorf("写入 unit 文件 %s: %w (需要 root 权限？)", path, err)
	}
	// best-effort daemon-reload; tolerated if not possible in this context
	if out, err := sysctlOutput("daemon-reload", ""); err != nil {
		log.Printf("daemon-reload: %s", strings.TrimSpace(out))
	}
	return path, nil
}

// serviceInspect builds the current state for the console.
func serviceInspect(cfgPath string) admin.ServiceInspect {
	exe, _ := os.Executable()
	real, err := filepath.EvalSymlinks(exe)
	if err == nil {
		exe = real
	}
	u, _ := currentRunUser()
	return admin.ServiceInspect{
		Unit:      serviceUnitName(),
		Installed: fileExists(serviceUnitPath()),
		Systemd:   hostSystemdActive(),
		Managed:   underSystemd(),
		Daemon:    os.Getenv("DEEPSEEK_DAEMON") == "1" && !underSystemd(),
		Exe:       exe,
		Config:    cfgPath,
		RunUser:   u,
		Version:   version,
	}
}

func sysctlOutput(action, unit string) (string, error) {
	var args []string
	if action != "" {
		args = append(args, action)
	}
	if unit != "" {
		args = append(args, unit)
	}
	out, err := exec.Command("systemctl", args...).CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// controlService runs a lifecycle action, with a graceful handoff for start
// when the current process is a `start` daemon or foreground (not systemd) so
// systemd cleanly owns the port. A "stop" after handoff/start returns fast.
func controlService(cfgPath string, action string) (admin.ServiceResult, error) {
	if action == "status" {
		out, err := sysctlOutput("status", serviceUnitName())
		if err != nil {
			return admin.ServiceResult{}, fmt.Errorf("%s", out)
		}
		return admin.ServiceResult{OK: out}, nil
	}
	installed := fileExists(serviceUnitPath())
	if !installed && action != "daemon-reload" {
		return admin.ServiceResult{}, fmt.Errorf("unit 文件未安装，请先点击【生成 unit 文件】（当前路径 %s）", serviceUnitPath())
	}
	if !hostSystemdActive() {
		return admin.ServiceResult{}, fmt.Errorf("systemd 未运行；请使用终端执行 scripts/install.sh 或手动安装")
	}

	// enable and disable never touch the running process or the port.
	if action == "enable" || action == "disable" {
		return sysctlResult(action)
	}
	if action == "daemon-reload" {
		return sysctlResult(action)
	}

	// start/stop/restart need systemd to control the live service. If the
	// current process is NOT under systemd (it was `start`-daemonized or run in
	// the foreground), a plain systemctl start would fail because WE still hold
	// the port. So we gracefully hand it over first.
	if action == "start" && !underSystemd() {
		return handoffToSystemd()
	}

	// stop/restart while NOT systemd-managed: there is no systemd-owned live
	// unit to control; a plain systemctl would be wrong. Point at the fork-based
	// restart (system page) or enable+start to become systemd-managed first.
	if (action == "stop" || action == "restart") && !underSystemd() {
		return admin.ServiceResult{}, fmt.Errorf("当前进程并非由 systemd 管理，无法用 systemctl %s。请在【系统】页使用“立即重启”（fork），或在【服务】页先【启动 start】交接给 systemd 后再重启/停止。", action)
	}

	// Already under systemd (or start of a systemd unit): plain control.
	if action == "start" {
		// systemd manages us; start is a no-op when already active.
		out, err := sysctlOutput("start", serviceUnitName())
		if err != nil {
			return admin.ServiceResult{}, fmt.Errorf("%s", out)
		}
		ok := "服务已处于 systemd 管理之下（start 无操作）。"
		if out != "" {
			ok = out
		}
		return admin.ServiceResult{OK: ok}, nil
	}
	return sysctlResult(action)
}

// handoffToSystemd hands the running service over to systemd so it owns the
// port and reads the SAME config file. It returns immediately (so the HTTP
// response is delivered) and lets a background goroutine close our listeners,
// start the systemd unit, then exit this process cleanly (no fork, no zombie).
func handoffToSystemd() (admin.ServiceResult, error) {
	log.Printf("handoff to systemd: preparing to close listeners gracefully")
	go func() {
		time.Sleep(1300 * time.Millisecond) // let the handshake HTTP response flush
		log.Printf("handoff to systemd: closing listeners, freeing the port")
		stopAll()
		time.Sleep(800 * time.Millisecond)
		out, err := sysctlOutput("start", serviceUnitName())
		if err != nil {
			log.Printf("handoff: systemd start 失败: %s", out)
			os.Exit(1)
		}
		log.Printf("systemd took over unit %s", serviceUnitName())
		os.Exit(0)
	}()
	return admin.ServiceResult{OK: "已交由 systemd 管理，当前进程即将平滑退出", Restarting: true}, nil
}

func sysctlResult(action string) (admin.ServiceResult, error) {
	unit := serviceUnitName()
	if action == "daemon-reload" {
		unit = ""
	}
	out, err := sysctlOutput(action, unit)
	if err != nil {
		return admin.ServiceResult{}, fmt.Errorf("%s", out)
	}
	ok := strings.TrimSpace(out)
	if ok == "" {
		ok = map[string]string{
			"enable":  "已启用（开机自启）",
			"disable": "已禁用",
			"start":   "已启动",
			"stop":    "已停止",
		}[action]
	}
	return admin.ServiceResult{OK: ok}, nil
}

func atomicWriteFile(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".unit-*")
	if err != nil {
		return err
	}
	tmppath := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmppath)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmppath)
		return err
	}

	if err := os.Chmod(tmppath, 0o644); err != nil {
		os.Remove(tmppath)
		return err
	}
	if err := os.Rename(tmppath, path); err != nil {
		os.Remove(tmppath)
		return err
	}
	return nil
}

// runServiceCLI implements `deepseek-server service <sub>`:
//
//	service install [--user U]  write unit + daemon-reload + enable (separate)
//	service enable             autostart only (does NOT start now)
//	service start              start now (with graceful handoff)
//	service stop|restart|status
//	service show               print the generated unit (no write)
func runServiceCLI(cfgPath string, args []string) int {
	if len(args) == 0 || args[0] == "help" || args[0] == "-h" {
		fmt.Print(`usage: deepseek-server service <sub>

  install             generate deepseek-server.service + enable (separate from start)
  enable              enable autostart (does not start now)
  start               start now (graceful handoff from a 'start' daemon / foreground)
  stop|restart        stop / restart the unit
  status              show service status
  show                print the unit file that would be installed
`)
		return 0
	}
	sub := args[0]
	switch sub {
	case "install":
		path, err := installServiceUnit(cfgPath)
		if err != nil {
			fmt.Fprintln(os.Stderr, "service install:", err)
			return 1
		}
		fmt.Printf("unit written: %s\n", path)
		if out, err := sysctlOutput("enable", serviceUnitName()); err != nil {
			fmt.Fprintf(os.Stderr, "warning: enable 失败（%s）。请确认 unit 目录属于 systemd 或用 web 控制台启用。\n", strings.TrimSpace(out))
		} else if out != "" {
			fmt.Println(out)
		}
		fmt.Printf("已启用开机自启（enable，未启动）\n现在启动请运行: deepseek-server service start   或   systemctl start %s\n",
			serviceUnitName())
		return 0
	case "show":
		exe, _ := os.Executable()
		u, g := currentRunUser()
		if e := os.Getenv("DEEPSEEK_SERVICE_USER"); e != "" {
			u = e
			if gu, err := user.Lookup(u); err == nil {
				if gg, gerr := user.LookupGroup(gu.Gid); gerr == nil && gg.Name != "" {
					g = gg.Name
				}
			}
		}
		b, err := renderServerUnit(exe, cfgPath, u, g)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return 1
		}
		os.Stdout.Write(b)
		return 0
	case "enable":
		return sysctlCLI("enable")
	case "start", "stop", "restart", "status":
		_, err := controlService(cfgPath, sub)
		if err != nil {
			fmt.Fprintln(os.Stderr, "service "+sub+":", err)
			return 1
		}
		fmt.Println("已执行:", sub)
		return 0
	default:
		fmt.Fprintln(os.Stderr, "unknown service subcommand:", sub)
		return 2
	}
}

func sysctlCLI(action string) int {
	out, err := sysctlOutput(action, serviceUnitName())
	if err != nil {
		fmt.Fprintln(os.Stderr, action+":", out)
		return 1
	}
	if out != "" {
		fmt.Println(out)
	}
	return 0
}
